---
- name: Copy Jenkins credentials
  template: src=scripts/credentials.sh dest=/tmp/credentials.sh  owner=jenkins group=jenkins mode=a+x

- name: Copy mailer plugin scripts
  template: src=email/manage_jenkins_plugin_mailer.groovy dest=/tmp/manage_jenkins_plugin_mailer.groovy owner=jenkins group=jenkins mode=a+x

- name: Copy credentials  scripts
  template: src=credentials/file_credentials.groovy dest=/tmp/file_credentials.groovy owner=jenkins group=jenkins mode=a+x

- name: Install Jenkins credentials
  command: sh credentials.sh
  register: shellout
  args:
     chdir: /tmp
     #executable: /bin/bash
  #become_user: jenkins


- name: Install Jenkins groovy credentials
  shell: CRUMB=$(curl -s 'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)');curl -H $CRUMB --data-urlencode "script=$(<./{{ item }})" http://localhost:8080/scriptText
  with_items:
   - file_credentials.groovy
   - manage_jenkins_plugin_mailer.groovy
  register: shellout
  args:
     chdir: /tmp
     executable: /bin/bash



- debug: var=shellout