---
- name: Install Jenkins plugins
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:8080/ install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
#  become: jenkins
#  become_user: jenkins
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins
