---
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_hostname: localhost
jenkins_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_directory: /var/lib/jenkins
jenkins_plugins:
  - ansicolor
  - build-timestamp
  - azure-credentials
  - azure-vm-agents
  - ace-editor
  - ant
  - antisamy-markup-formatter
  - authentication-tokens
  - bouncycastle-api
  - branch-api
  - build-timeout
  - cloudbees-folder
  - copyartifact
  - credentials
  - credentials-binding
  - display-url-api
  - docker-build-step
  - docker-commons
  - durable-task
  - email-ext
  - envinject
  - external-monitor-job
  - git
  - git-client
  - git-server
  - github
  - github-api
  - github-branch-source
  - github-organization-folder
  - golang
  - gradle
  - greenballs
  - handlebars
  - icon-shim
  - jackson2-api
  - javadoc
  - jquery-detached
  - junit
  - ldap
  - mailer
  - mapdb-api
  - matrix-auth
  - matrix-project
  - maven-plugin
  - momentjs
  - nodejs
  - pam-auth
  - pipeline-build-step
  - pipeline-graph-analysis
  - pipeline-input-step
  - pipeline-milestone-step
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-view
  - plain-credentials
  - publish-over-ssh
  - resource-disposer
  - robot
  - s3
  - scm-api
  - scm-sync-configuration
  - script-security
  - ssh
  - ssh-agent
  - ssh-credentials
  - ssh-slaves
  - structs
  - subversion
  - timestamper
  - token-macro
  - windows-slaves
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-cps-global-lib
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
  - ws-cleanup
  - xvfb
  - zentimestamp

jenkins_repo_url: deb http://pkg.jenkins-ci.org/debian-stable binary/
jenkins_repo_key_url: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
jenkins_version: 2.32.3

jenkins_jobs:
  - jobtemplate

docker_edition: ce

# docker-ce is the default package name
docker_pkg_name: "{{ 'docker-ee' if docker_edition == 'ee' else 'docker-ce' }}"
docker_apt_cache_valid_time: 600
docker_aufs_enabled: true

# Set to 'yes' or 'true' to enable updates (sets 'latest' in apt module)
update_docker_package: no
# docker dns path for docker.io package ( changed at ubuntu 14.04 from docker to docker.io )
docker_defaults_file_path: /etc/default/docker

# Place to get apt repository key
apt_key_url: https://download.docker.com/linux/ubuntu/gpg
# apt repository key signature
apt_key_sig: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
# Name of the apt repository for Docker CE or EE
apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename|lower }} stable"
